### PR TITLE
updated extractor docs to clarify confusion about semantic scenes

### PR DESCRIPTION
**Pull request by mpiseno**
## Motivation and Context

There was some confusion in [this](https://github.com/facebookresearch/habitat-sim/issues/1825#issuecomment-1233198816) issue about semantic output from the image extractor. I updated the docs to be more clear about this.

## How Has This Been Tested

Ran the docs build script and viewed them locally.

## Types of changes

- [x ] Docs change / refactoring / dependency upgrade

### CODE REVIEW

**Comment by mpiseno** [comment]
Sorry for the delay on this. Right now I've just updated the docs to clarify the use of semantic outputs and removed the semantic output from part 1 of the tutorial. 

Since HM3D seems to be the preferred dataset for semantic annotations, I want to try updating the tutorial to use that dataset instead. I'm just waiting for an API token from MatterPort for this. Until I have that done, I've marked this PR as a draft.

cc @aclegg3 @dhruvbatra

**Comment by dhruvbatra** [comment]
Thank you!

**Comment by aclegg3** [comment]
> @aclegg3 @dhruvbatra This update should be good to go. Let me know what you think. I am failing circleci tests because of some credentials issues I think. Is there any way to run these from your side before merging?

Thanks for updating things. :+1: 

Looks like your branch is pretty far behind `main` at this point, so likely the CI failures are related to dependency bugs and lab api updates. I'd suggest merging those changes into this branch so we can get a better picture of the test status. I doubt there will be any conflicts given the isolation of these changes.

**Comment by mpiseno** [comment]
> Looks like your branch is pretty far behind `main` at this point, so likely the CI failures are related to dependency bugs and lab api updates. I'd suggest merging those changes into this branch so we can get a better picture of the test status. I doubt there will be any conflicts given the isolation of these changes.

Thanks! I updated my version of main and did some merging of files. But if you look at the tests that are failing now, it says "Unable to locate package llvm-10" for the python_lint test, and "anaconda login: error: argument --password: expected one argument" for the build_condo_osx-1 test (this error was there before I merged). Looks like my circleci config is the same as main, so I'm not sure why this would happen.

**Comment by aclegg3** [comment]
>  "Unable to locate package llvm-10" for the python_lint test,

This is a known issue and we're working on a fix

> and "anaconda login: error: argument --password: expected one argument" for the build_condo_osx-1 test (this error was there before I merged). Looks like my circleci config is the same as main, so I'm not sure why this would happen.

I think the repo permissions may not be available from your fork. Don't worry about the conda build tests.

**Comment by aclegg3** [comment]
Looks like you have stale versions of the dependencies (e.g. Magnum) in your PR. You'll want to:
1. check out and pull main
2. build main (or otherwise pull the correct submodule versions)
3. checkout your branch
4. commit the submodule versions from main

**Pull request closed without merging**
