### PR TITLE
Use Eigen integration for SceneNode

### PR DESCRIPTION
**Pull request by mosra**
## Motivation and Context

Uses Magnum's [EigenIntegration](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1EigenIntegration.html) to do accident-free conversion between Magnum and Eigen types. This is just a tiny part, it will get further used for the Python API to get numpy/Eigen/Magnum conversions. What already works [on the Python side](https://doc.magnum.graphics/python/) (even without any Eigen/numpy integration code) is conversion between vector types thanks to the implicit construction from tuples. For example:

```pycon
>>> import numpy as np
>>> from magnum import Vector3
>>> b = np.array([1, 2, 3])
>>> c = Vector3(b)
>>> c
Vector(1, 2, 3)
```

For matrix types I want to *ensure* there are no issues related to conversion of row-major/column-major layout and so the conversion needs to be something more than that. Right now pybind11 is not obeying my orders so I'll sleep over this and hopefully come with a working solution.

## How Has This Been Tested

Code compiles and the viewer navigation works when trying locally.

I just added a submodule and enabled it in CMake and likely forgot to do something important, please let me know if there are any issues.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by erikwijmans** [comment]
This currently doesn't build with in-tree Eigen.  Adding

```
  set(EIGEN3_INCLUDE_DIR "${DEPS_DIR}/eigen-git-mirror")
  set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${DEPS_DIR}/eigen-git-mirror/cmake")
```

here https://github.com/facebookresearch/habitat-sim/blob/eigen-integration/src/cmake/dependencies.cmake#L20 solves that.

**Comment by mosra** [comment]
Whoops, sorry. Worked on my machine; I blame having `FindEigen.cmake` in CMake's system module path. Pushed a fixed version.

On a related note -- I'm seeing various things in the build scripts that are not considered best CMake practices by todays standards (for example, global `include_directories()` instead of adding include paths only for targets that actually need them), would you be interested in a PR that updates the build scripts?

**Comment by msavva** [comment]
@mosra PRs to improve the cmake setup would be much appreciated. :-)

**Comment by erikwijmans** [comment]
The `set(EIGEN3_INCLUDE_DIR "${DEPS_DIR}/eigen-git-mirror")` is needed also :)

**Comment by mosra** [comment]
:see_no_evil: ... for some reason my brain thought `include_directories(SYSTEM "${DEPS_DIR}/eigen-git-mirror")` and `set(EIGEN3_INCLUDE_DIR "${DEPS_DIR}/eigen-git-mirror")` is the same line and so I removed the "duplicate". Fixed, sorry again.

**Comment by erikwijmans** [comment]
> @mosra PRs to improve the cmake setup would be much appreciated. :-)

Seconded!

**Comment by mosra** [comment]
Opened https://github.com/facebookresearch/habitat-sim/issues/42 to track the CMake stuff, I'll look into it once the initial Magnum Python bindings are done.

**Comment by dhruvbatra** [comment]
Seconded. Fresh pull and build works on MacOS.

**Pull request merged**
