### PR TITLE
Configurable physics object semantics

### PR DESCRIPTION
**Pull request by aclegg3**
## Motivation and Context
When adding arbitrary objects to the scene, users may want to configure the semantic ID as in issue #320.

With the current implementation we enable integer setting of the semanticId in the configuration file. This requires the user to know the mapping between semantic label and integer id. This should be improved in the future to allow specifying new or existing object classes instead of integer ids only.

This also changes `SceneNode::id_` assignment in `addComponent` to occur for all `SceneNode`'s associated with an object (even those not containing meshes). 

## How Has This Been Tested

Added a C++ test.

Local testing in Replica apartment_0 with `<object>.phys_properties.json` updated to specify:
- cheezit
  - `"semantic id": 10`
- banana
  - `"semantic id": 5`
- chefcan
  - `"semantic id": 2`

rgb_scene:
test rgba 00000

before object semantics:
test sem 00000

after object semantics:
test sem 00000

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aclegg3** [comment]
https://github.com/facebookresearch/habitat-sim/pull/413#discussion_r362987043

@msavva, @dhruvbatra, @mosra 

This discussion seems very relevant to this PR. 😄 

🤔 My understanding was that the `SceneNode::id_` is the semantic type identifier of the object. Therefore when a mesh is rendered with no vertex level semantic identifier, it is used to flat shade the mesh stored at the node. 

I arrived at this conclusion from this issue discussion: https://github.com/facebookresearch/habitat-sim/issues/336#issuecomment-549017586.

This PR is about exposing that value for modification and configuration. 

Big distinction here is that the `PhysicsManager::existingObjects_` is a map of individual object instances to integer ids (e.g., could be 10 of the same asset, but each would have a unique id here. When referring to these locally in the code, I usually call them `objectId`. However, all of these objects may have the same `SceneNode::id_`. If we want scene nodes to somehow refer back to their id in `PhysicsManager::existingObjects_`, then we should create a new id for this purpose and rename the existing `SceneNode::id_` used for semantic rendering to something more obvious unless there is another purpose for this value in the current implementation.

Open to thoughts! 😀

**Comment by bigbike** [comment]
continue the discussion (#413) here:
>I don't know that it changes the guaranteed relationship between a rigid object and a SceneNode or the need to id them.
The 1:1 correspondence between a rigid object and a SceneNode is guaranteed. And each rigid object certainly needs an id.
My opinion is that you can put this 'id' in the `RigidObject`, not in the 'SceneNode'. physics-specific properties should not be added to the base class "SceneNode'.

**Comment by bigbike** [comment]
Clarify: my reply is based on my current understanding:
- Only the physics-enabled objects have object ids. The other objects (e.g., the scene, the cameras) do not have ids.
- We give ids to objects, not scene graph nodes. So each scene graph node does not have an id. (the existing id_ in SceneNode is used to store semantic info.)

**Comment by kylevedder** [comment]
Has there been any additional work on this PR or others to get object semantics for physics objects merged? This is a blocking issue for our work so we're willing to devote engineering resources to getting this feature added.

**Comment by aclegg3** [comment]
> Has there been any additional work on this PR or others to get object semantics for physics objects merged? 

Hey @kylevedder, thanks for checking in on this. 👍 
We have recently picked back up on this feature as other users are also blocked here. We plan to complete this in the next week or two. Stay tuned.

**Comment by aclegg3** [comment]
Purpose of this PR filled with #668. Closing.

**Pull request closed without merging**
