### PR TITLE
Activate objects when moved

### PR DESCRIPTION
**Pull request by aclegg3**
## Motivation and Context

Context: I noticed that edge cases existed where discrete collision detection results were not accurate. Investigation revealed that when a sleeping object was moved kinematically into contact with another sleeping object, the contact would be ignored by discrete collision detection routine.

After investigation, I concluded that the most sensible solution would be to force wake any sleeping object which is moved kinematically. This handles the current bug in discrete collision checking as well as making more sense (teleporting and object near a sleeping island could cause reactions and so the island should be awoken).

BREAKING CHANGE: any downstream code taking advantage of this bug will no longer work as it did previously. This fix will create some minimal additional overhead as kinematic motion of a sleeping object may wake other nearby islands during simulation. 

Note that unmoved sleeping objects will not wake from discrete collision checking with kinematic shapes unless step_physics is called while the objects are in contact. This should continue to efficiently support use cases such as checking for valid contact-free states between simulation steps.

## How Has This Been Tested

Added new test scenarios to the python physics test.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jturner65 — APPROVED** [review]
LGTM.

**Comment by aclegg3** [comment]
Looks like joint constraint pytest is reporting different torques after this change. I didn't see any change in behavior from the videos other than new random numbers. Perhaps this test was faulty to begin with. Removed the assertion.

**Comment by jturner65** [comment]
> Looks like joint constraint pytest is reporting different torques after this change. I didn't see any change in behavior from the videos other than new random numbers. Perhaps this test was faulty to begin with. Removed the assertion.

I'll take a look at this in the morning, just to be sure.

**Review by 0mdc — APPROVED** [review]
LGTM!

**Pull request merged**
