### PR TITLE
Better check of type before converting vector to quaternion

### PR DESCRIPTION
**Pull request by vincentpierre**
## Motivation and Context

Need a better way to check wether something is a quaternion before attempting to convert it. Not everything we will pass through will be either a list or a np.array so I added a better check. 

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Skylion007** [comment]
Technically, it shouldn't be checking if it's a list, but probably a Sequence, SizedSequence, or Iterable. Point still stands though.

**Comment by mosra** [comment]
Tangential / FYI: I remember that back in 2019 we discussed getting rid of the Python Quaternion package in favor of the [builtin Magnum Quaternion class](https://doc.magnum.graphics/python/magnum/Quaternion/), significantly simplifying the Python/C++ bindings and data transfer as a result (and allowing us to eventually ditch Eigen also, since it's only really used for the data types, not any algorithms). Back then the idea got abandoned because it would mean Habitat-Lab would depend on Magnum, and that was a no-go. But maybe nowadays it's no longer a problem? 

Mentioning this mainly so you're aware of the original design decisions, not that I would *demand* any complex changes to be made ;)

**Comment by Skylion007** [comment]
@mosra Yeah, I don't think that's as much of a problem given how tightly magnum is integrated into the robotics part of habitat-lab.

**Review by Skylion007 — APPROVED** [review]

**Review by rpartsey — APPROVED** [review]

**Comment by Skylion007** [comment]
This can be closed now, right?

**Pull request closed without merging**
