### PR TITLE
Rebase AO prototype.

### PR DESCRIPTION
**Pull request by aclegg3**
## Motivation and Context

Rebase the AO demo branch up to current master branch.

Also merge #729, relocating tinyXML to src/deps and cleaning up URDF Parser.

New features include:
- PBR materials/shader (and lighting changes)
  - Note: breaking change on visualizations. Things will look different now.
- SceneDataset and MetadataMediator loading (instancing to come).
  - Support new configuration files
- Viewer updates:
  - `LOOK` mouseMode
  - SPACE pause/start simulation
  - full app refactored through `Simulator` API
- Added Point-to-Point constraints to Simulator API (python bindings TODO)
- Various physics bugfixes.

## How Has This Been Tested

Local testing with viewer and python URDF script.

TODO: more testing before final merge.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Skylion007** [comment]
@aclegg3 Most of the tests are failing because of the C++ linter. Have we still not moved tinyXML in src/deps?

**Comment by aclegg3** [comment]
> @aclegg3 Most of the tests are failing because of the C++ linter. Have we still not moved tinyXML in src/deps?

Planning to pull the tinyXML change from #729 after this rebase.

**Comment by Skylion007** [comment]
@aclegg3 TinyXML still needs to be moved to src/deps

**Comment by aclegg3** [comment]
Merging this PR to the prototype. 
Looks like CI Bullet version is out of sync, especially for the multi-body API. We should think about pulling Bullet in as a submodule soon to address this.

**Pull request merged**
