### PR TITLE
No shared sim

### PR DESCRIPTION
**Pull request by erikwijmans**
## Motivation and Context

It's time to get rid of the sharing the instance of the simulator among all the tests hack.  I also added an explicit test that the current test_sensors was implicitly testing -- making sure reconfigure actually swaps the scene correctly.

This also allows us to enable parallel testing through https://github.com/browsertron/pytest-parallel so total test time is actually reduced!

## How Has This Been Tested

Via the tests

## Types of changes

 Docs change / refactoring / dependency upgrade

### CODE REVIEW

**Comment by Skylion007** [comment]
@erikwijmans You need to add the pytest-plugin here as well: https://github.com/facebookresearch/habitat-sim/blob/1728d6e7d7e5583f1634945e66182769c414bb86/setup.py#L383

**Comment by erikwijmans** [comment]
> @erikwijmans You need to add the pytest-plugin here as well:

I didn't add any flags that plugin for `setup.py test` so I don't it is needed.

**Comment by Skylion007** [comment]
But doing it will automatically install the pytest plugins, so it should still be done for the end user.

**Comment by erikwijmans** [comment]
> But doing it will automatically install the pytest plugins, so it should still be done for the end user.

But why install something they don't need?  That plugin does nothing by default, so unless they know to specify the flag (and want to specify it), it won't do anything.  I didn't add anything by default as I don't want to force everyone to run parallel testing locally.

**Comment by Skylion007** [comment]
Fair enough, I guess it's not necessary like the other pytest ones.

**Review by Skylion007 — APPROVED** [review]

**Review by jturner65 — APPROVED** [review]
LGTM

**Pull request merged**
