### PR TITLE
Update to latest Magnum with configuration iteration and support for new meshoptimizer

### PR DESCRIPTION
**Pull request by mosra**
## Motivation and Context

This brings mostly:

- Support for [configuration value/group iteration](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Configuration.html#Utility-Configuration-iteration), requested by @jturner65
- Support for MeshOptimizer 0.16 and its updated simplifier, reuqested by @eundersander. Should help the artifacts in https://github.com/facebookresearch/habitat-sim/pull/1057.

But also:

 * Support for OpenEXR 3.0 (so the package installed from Homebrew can work with it, which is also slowly inching towards an ability to use it as a CMake subproject)
 * Support for Glslang 11.4 (which fixes the *really strange* linker bug @bigbike had when attempting to use `magnum-shaderconverter` on macOS some time ago, don't even get me started on the aspects of this project buildsystem quirks)
  * Support for SPIRV-Tools 2021.1 

## How Has This Been Tested

I was very angry for a few days, but eventually the CIs stopped giving me a red light.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
@mosra Wow, you buried the lead with the new Corrade::Pair class. We use std::pair everywhere currently, is it ready to swap over all our std::pair to Corrade::Pair in the codebase?

**Review by jturner65 — APPROVED** [review]
LGTM.  I can't wait to use this stuff. Thanks!

**Comment by mosra** [comment]
> We use std::pair everywhere currently

@Skylion007 ... and you can continue to do so, the corrade `Pair` is convertible to the STL equivalent so in most cases you won't even realize it's a different type. Same is with string (view)s and `std::unique_ptr` already, I don't think Habitat directly uses the `Pointer` anywhere and yet it works :)

**Comment by Skylion007** [comment]
@mosra Yeah, I was just referring to the perf advantages with it being trivially copyable and all. It would be good to change our code over, no?

**Comment by Skylion007** [comment]
This is probably the only struct that can benefit though: https://github.com/facebookresearch/habitat-sim/blob/34ec4f664742e762107ef606208e66259e051775/src/esp/assets/MeshMetaData.h#L59

**Comment by mosra** [comment]
> It would be good to change our code over, no?

I don't think it'd matter in cases where just single instances are used. In Magnum I plan to use it in hashmap internals and the RenderGraph and there I expect a significant difference on reallocation, copying 10k pairs via memcpy will definitely be faster than looping over and calling copy constructors because `std::is_trivially_copyable` says no.

I see no other complaints, so merging :P (Did anybody witness any perf improvements from the last PR?)

**Pull request merged**
