### PR TITLE
Updated Circle CI images to use update cimg namespace

### PR DESCRIPTION
**Pull request by mathfac**
## Motivation and Context
Our nightly conda packages were broken for sometime. One of the reasons was using old version of the circleci image for document build.

```
sudo apt-get install -yq \
>       rsync
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libpopt0
Suggested packages:
  openssh-server
The following NEW packages will be installed:
  libpopt0 rsync
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 361 kB of archives.
After this operation, 882 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu disco/main amd64 libpopt0 amd64 1.16-12
  404  Not Found [IP: 91.189.88.142 80]
Err:2 http://archive.ubuntu.com/ubuntu disco/main amd64 rsync amd64 3.1.3-6
  404  Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/popt/libpopt0_1.16-12_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/r/rsync/rsync_3.1.3-6_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by mathfac** [comment]
Brought back filtering on master branch for doc build.

**Comment by mathfac** [comment]
Decided to trigger conda nightly build to test that part and build fresh package.

**Review by erikwijmans — APPROVED** [review]
LGTM once the triggers have be uncommented

**Comment by mathfac** [comment]
I am seeing occasional failures with `python setup.py develop --all` for Habitat Lab step:
```
Using /home/circleci/miniconda/envs/habitat/lib/python3.6/site-packages/oauthlib-3.1.0-py3.6.egg
Finished processing dependencies for habitat==0.1.6
Collecting package metadata (current_repodata.json): - \ | / - \ | / - \ | / - \ | / - WARNING conda.core.index:push_record(255): Skipping pypi/pypi::gym-0.18.0-pypi_0 due to InvalidSpec: 3.
\ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done
Solving environment: - \ failed with initial frozen solve. Retrying with flexible solve.

InvalidVersionSpec: Invalid version '3.': empty version component
```
Merging and will address once it will be replicated.

**Comment by eugenelyj** [comment]
It is strange that `InvalidVersionSpec: Invalid version '3.': empty version component` still exist in `habitat-sim-0.1.7.2021.05.12-py3.8_headless_linux` of nightly conda packages and it prevent me from any conda install operation. Anyone knows the reason?

**Pull request merged**
