### PR TITLE
Disable broken JS test and make --no-web-apps the default

### PR DESCRIPTION
**Pull request by eundersander**
## Motivation and Context

This javascript test is broken, probably just due to timing out. Habitat JS support is still experimental so it's not vital to have this JS tested for now. We'll revisit CI for the JS build in the future.

I'm also making `--no-web-apps` the default for the JS build. This is a simpler build that doesn't rely on npm or webpack and should make the Habitat JS build more accessible and easy to understand for new folks looking to experiment here.

More background and specifics: the Habitat JS build is a version of our C++ library that is emscripten-compiled into a WebAssembly module (a `.wasm` file). This can be imported into a webpage and used by Javascript. Our legacy web apps (bindings.html, viewer.html) are examples of using the Habitat JS build, but they're not a required part of the JS build. 

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by 0mdc — APPROVED** [review]
LGTM!

**Review by aclegg3 — APPROVED** [review]
Thanks!

**Review by jturner65 — APPROVED** [review]
If you rebase this PR on top of main now, you should get a clean slate.

**Comment by jturner65** [comment]
Took the liberty of rebasing this to test it, hopefully that's ok :)

**Comment by aclegg3** [comment]
> Took the liberty of rebasing this to test it, hopefully that's ok :)

Thanks, let's merge it ASAP once tests are done.

**Pull request merged**
