### PR TITLE
--Fix issues with hab lab doc-building.

### PR DESCRIPTION
**Pull request by jturner65**
## Motivation and Context
Removes setting pip_interop_enabled to true in conda builds.  This is expected to address CircleCI issue with documentation building.

## How Has This Been Tested
C++ and python tests.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mathfac — APPROVED** [review]
Thank you for addressing this.
>pip_interop_enabled: This feature is still experimental and is therefore off by default.
>Setting pip_interop_enabled to True may slow down conda

We should be careful with enabling experimental features.

**Comment by Skylion007** [comment]
The Collab install is very sensitive so I would advise against disabling PIP_INTEROP in the collab install. Doing so in the circleci should be fine though.

**Review by Skylion007 — CHANGES_REQUESTED** [review]

**Comment by jturner65** [comment]
We've decided that since this change does not have a direct bearing on the issue it was supposed to be addressing, we will not add this.

**Comment by jturner65** [comment]
Upon -further- discussion :) @Skylion007  and I decided that perhaps removing the one line specifying interop in the config.yaml might in fact address the issue we are experiencing, so this PR is now re-opened for business :)

**Review by Skylion007 — APPROVED** [review]
Let's see if this fixes it.

**Pull request merged**
