### PR TITLE
Adds a jupyter notebook illustrating simple use cases

### PR DESCRIPTION
**Pull request by bhavanajain**
## Motivation and Context
The `habitat-sim-demo.ipynb` notebook illustrates how to specify the simulator and agent configuration, print semantic annotations of a scene. It also visualises the RGB, semantic and depth observations obtained by executing a random sequence of actions. 

Todo: Add a code block to walk along a shortest path and visualise observations along the way. 
 

## How Has This Been Tested
Let's use [nbval](https://github.com/computationalmodelling/nbval) to test the jupyter notebooks. 
`pip install nbval`
`pytest --nbval-lax notebooks/habitat-sim-demo.ipynb`
Note: The --nbval option will collect and test notebook cells, comparing their outputs with those saved in the file whereas the --nbval-lax option collects notebooks and runs them, failing if there is an error.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by erikwijmans** [comment]
For the first cell, you can just do this for adding things to the path:

```
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), ".."))
```

**Comment by erikwijmans** [comment]
The test scene path should be relative and follow what we have been doing for other paths:

```
test_scene = "data/scene_datasets/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb"
```

**Comment by erikwijmans** [comment]
You also only need to do `import habitat_sim`.  All the things that are part of the bindings can be accessed from that.  i.e. `hsim.SimulatorConfiguration` -> `habitat_sim.SimulatorConfiguration`.  The `hsim` thing is done in the implementation of the package to avoid circular imports.

**Comment by erikwijmans** [comment]
Let's put the agent at a reasonably interesting starting location, instead of a random one, which may be weird,

```
initial_state = habitat_sim.AgentState()
initial_state.position = np.array([0.0, 0.072447, 0.0])
agent = sim.initialize_agent(sim_settings["default_agent"], initial_state)
```

gives an interesting initial location

**Comment by erikwijmans** [comment]
> For the first cell, you can just do this for adding things to the path:
> 
> ```
> import sys
> import os
> sys.path.insert(0, os.path.join(os.getcwd(), ".."))
> ```

On second thought, the notebook shouldn't mess with the pythonpath at all.  People can either use `export PYTHONPATH=/path/to/habitat-sim` or they will have done `python setup.py install`

**Comment by mathfac** [comment]
@bhavanajain, @erikwijmans, do we plan to land this PR before version cut?

**Comment by bhavanajain** [comment]
@mathfac Yes, working on it today. Should be ready to land before afternoon.

**Comment by bhavanajain** [comment]
For testing the notebooks, we can use [nbval](https://github.com/computationalmodelling/nbval). To test a notebook,
`pip install nbval`
`pytest --nbval-lax notebooks/habitat-sim-demo.ipynb`
Note:  The `--nbval` option will collect and test notebook cells, comparing their outputs with those saved in the file whereas the `--nbval-lax` option collects notebooks and runs them, failing if there is an error.

**Comment by erikwijmans** [comment]
One final change request:
```
print('House has %s levels, %s regions and %s objects' % (len(scene.levels), len(scene.regions), len(scene.objects)))
```
->
```
print(f"'House has {len(scene.levels)} levels, {len(scene.regions)} regions and {len(scene.objects)} objects")
```

**Pull request closed without merging**
