### PR TITLE
Remove unused and potentially confusing agent dynamic properties

### PR DESCRIPTION
**Pull request by aclegg3**
## Motivation and Context

As pointed out by user issues (e.g. #1401 ) Habitat Agents have unused dynamic properties: velocity, mass, acceleration, friction, restitution. This PR removes those properties to reduce confusion. When an Agent is attached to a dynamic object (e.g. robots and rigid objects) dynamic properties should be queried from the physics object interface directly ([ManagedBulletRigidObject](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.ManagedBulletRigidObject.html) or [ManagedBulletArticulatedObject](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.ManagedBulletArticulatedObject.html)).

## How Has This Been Tested

I couldn't find any references to these in our code, but if anyone knows of any existing uses which would be negatively impacted by this cleanup we can potentially think of an alternative to removing them.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
It would be nice to pass through some this info through Bullet if it supports it though.

**Comment by aclegg3** [comment]
> It would be nice to pass through some this info through Bullet if it supports it though.

Sure, but a base Habitat Agent does not have a `Bullet` embodiment and won't know it has one attached unless we add more sophisticated extensions of Agent to track this. I propose we add these back if/when we make that change rather than keeping them as part of the base agent.

**Comment by Skylion007** [comment]
Looks like the Habitat-Lab configs currently do specify these properties so we should link it up to the physics manager if appropriate.

**Review by mathfac — APPROVED** [review]
Yes, as @Skylion007 said we need to send PR to Habitat Lab first to remove field from the [HabLab default config and others](https://github.com/facebookresearch/habitat-lab/blob/368007d067119518124e9d632f4769ee1d5898e4/habitat/config/default.py#L353-L357).

**Pull request merged**
