### PR TITLE
[utils/viewer] move viewer code out of esp/gfx library

### PR DESCRIPTION
**Pull request by msbaines**
## Motivation and Context

Viewer code does not really belong in the esp/gfx library.

## How Has This Been Tested

Ran viewer and took a screenshot.

## Types of changes

- [X] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bigbike** [comment]
@msbaines : The filename is supposed to start with a capital letter. So it should be "Viewer.cpp", not "viewer.cpp".

**Comment by msbaines** [comment]
> @msbaines : The filename is supposed to start with a capital letter. So it should be "Viewer.cpp", not "viewer.cpp".

Yeah, I wasn't sure what the convention was. Whether to name it Viewer.cpp or keep it as viewer.cpp. I kept it as viewer.cpp since that was the current name of this file. It is also consistent with utils/datatool/datatool.cpp. viewer and datatool are the name of the binaries so maybe this convention is OK. I don't have strong opinions on this as long as we are consistent. I am happy to rename viewer.cpp to Viewer.cpp but then we should also change datatool.cpp to Datatool.cpp.

**Comment by bigbike** [comment]
Oh, I see.
When we started this project last year, I remembered our decision was to follow the FB C++ naming conventions found internally. You can search CppStyle internally. I think we should follow it.

**Comment by bigbike** [comment]
Yes, we may need to change the datatool.cpp as well.

**Pull request merged**
