### PR TITLE
[WIP] [esp/progmesh] new utility for reducing semantic mesh complexity

### PR DESCRIPTION
**Pull request by msbaines**
Based on https://github.com/melax/sandbox/blob/e436aa9/bunnylod/progmesh.cpp

Paper: http://www.melax.com/polychop

Takes a few minutes to reduce 17DRP5sb8fy_semantic.ply from
1.5M vertices to 0.5M vertices, reducing filesize from 71M to 21M.

Usage:
$ progmesh data/scene_datasets/mp3d/17DRP5sb8fy/17DRP5sb8fy_semantic.ply 17DRP5sb8fy_semantic.ply 500000

## Motivation and Context

Speedup semantic observation

## How Has This Been Tested

Tested on 17DRP5sb8fy_semantic.ply from mp3d dataset. Could see no difference between original mesh and reduced vertex mesh.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by msbaines** [comment]
Work in progress. Plan to optimize and cleanup the code.

However, don't plan to change the algorithm so output should not change. Therefore, folks can start playing with it now and give feedback on the resulting mesh.

**Comment by aclegg3** [comment]
> Work in progress. Plan to optimize and cleanup the code.
> 
> However, don't plan to change the algorithm so output should not change. Therefore, folks can start playing with it now and give feedback on the resulting mesh.

Thanks for working on this, I'm happy to use it to reduce meshes for more efficient collisions. We should make the `objectId` part optional for this purpose. Also seems very quick for smaller meshes.

Would be nice to make this dynamic and operate on internal `MeshData` objects.

**Comment by Skylion007** [comment]
Doesn't compile on Linux because progmesh.cpp is missing #include <cstring> .

**Comment by eundersander** [comment]
Closing this stale PR.

**Pull request closed without merging**
