### PR TITLE
Coordinate system tutorial

### PR DESCRIPTION
**Pull request by rpartsey**
## Motivation and Context

An updated version of https://github.com/facebookresearch/habitat-sim/pull/1498.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rpartsey** [comment]
@dhruvbatra It turned out that even though the PR https://github.com/facebookresearch/habitat-sim/pull/1498 was open on Sep 22, 2021, the code was written so well that it works like a charm even after merging current main. I've also updated code to be more similar to other sim tutorials. 

The updated cached colab version of the tutorial can be found [here](https://colab.research.google.com/drive/1-7IT_vszRt5D7Ze7rWN2tioXEhjNvFzQ). Let me know if you wand something specific to be added/addressed.

Should I also add a corresponding doc page for the aihabitat website?

**Comment by dhruvbatra** [comment]
Yeah, @eundersander does has a habit of writing code like that 😄. Cached colab tutorial looks great! No comments. 

Yes, let's add a corresponding docs page and list it in the docs. Thanks @rpartsey!

**Comment by rpartsey** [comment]
Looks like one of flaky tests is failing 3/3 times. The functionality that may impact the test wasn't touched and it is not reproducible on the other PRs.

**Comment by rpartsey** [comment]
> Looks like one of flaky tests is failing 3/3 times. The functionality that may impact the test wasn't touched and it is not reproducible on the other PRs.

Fixed on habitat-lab side in scope of https://github.com/facebookresearch/habitat-lab/pull/1134.

**Review by dhruvbatra — APPROVED** [review]

**Pull request merged**
