### PR TITLE
[esp/agent] rename lookLeft/Right to turnLeft/Right

### PR DESCRIPTION
**Pull request by msbaines**
lookLeft is not correct. We are actually turning the agent body.
Since only SimulatorWithAgents is using this it should only
affect WebGL. Fixed a bunch of places where Agent.h was included
but not used in order to confirm that only WebGL was affected.

## Motivation and Context

I want to clean up and rationalize actions in Agent.h before adding lookUp and lookDown.

## How Has This Been Tested

Verified that turning still works in WebGL demo.

## Types of changes

- [X] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mathfac** [comment]
Looks like more things need to be changed: https://github.com/facebookresearch/habitat-sim/search?q=lookLeft&unscoped_q=lookLeft.

**Comment by erikwijmans** [comment]
> Looks like more things need to be changed: https://github.com/facebookresearch/habitat-sim/search?q=lookLeft&unscoped_q=lookLeft.

Those are fine.  The difference between a lookLeft and turnLeft isn't the implementation, its whether or not it operates on the agent's body or on the sensors.

**Comment by msbaines** [comment]
> Looks like more things need to be changed: https://github.com/facebookresearch/habitat-sim/search?q=lookLeft&unscoped_q=lookLeft.

All the ones that are relevant should now be addressed.

**Comment by msbaines** [comment]
> Those are fine. The difference between a lookLeft and turnLeft isn't the implementation, its whether or not it operates on the agent's body or on the sensors.

I agree. That's why I'm making this change. In the cases I've addressed with this change, we were moving the agents body and calling it lookLeft.

**Comment by msbaines** [comment]
> > Those are fine. The difference between a lookLeft and turnLeft isn't the implementation, its whether or not it operates on the agent's body or on the sensors.
> 
> I agree. That's why I'm making this change. In the cases I've addressed with this change, we were moving the agents body and calling it lookLeft.

To handle look, we should make the sensor a separate node (that is a child of the agent node) in the scene graph if that is not the case already.

**Comment by erikwijmans** [comment]
> To handle look, we should make the sensor a separate node (that is a child of the agent node) in the scene graph if that is not the case already.

Yep, that is exactly how it is done :)

**Comment by erikwijmans** [comment]
> I agree. That's why I'm making this change. In the cases I've addressed with this change, we were moving the agents body and calling it lookLeft.

Yeah, we made this change on the python side, but never put it into cpp

**Pull request merged**
