### PR TITLE
ReplicaCAD v1.3

### PR DESCRIPTION
**Pull request by aclegg3**
## Motivation and Context

Updates the default downloader version for ReplicaCAD to v1.3.

Changes with v1.3:
- Updated synthetic 105 variations with baked stage, geometry consistent with baked scenes.
- New NavMesh files for all scenes including STATIC and articulated (URDF) furniture.
- Added inner surface to objects/frl_apartment_kitchen_utensil.glb to fix interior culling.
- Added Receptacle annotation to most articulated furniture to support rearrangement tasks.
- Added global furniture receptacle annotations to baked scenes.
- Updated fridge interior for consistency b/t synthetic and baked scenes.
- Added collision group tags to articulated furniture for better performance when initialized as STATIC with fixed_base.
  - Added dynamic variants of URDFs for non-static use cases.
- All modified scene configs such that articulated objects have automatically enforced joint limits by default.
- Added "settled" states for dynamics scenes (i.e., apt_0...5) to reduce object movement (e.g. dropping onto surfaces) upon scene initialization.
- Adjusted all 105 variation layouts to reduce object inter-penetration artifacts.
- Additional minor fixes and modifications

## How Has This Been Tested

Locally

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jturner65 — APPROVED** [review]
LGTM

**Comment by dhruvbatra** [comment]
I tested it. 

Testing with C++ and python viewer works perfectly. Testing with ReplicaCAD_quickstart.py results in an all-black screen recording. Log attached. 
[log.txt](https://github.com/facebookresearch/habitat-sim/files/8173627/log.txt)

**Review by Skylion007 — APPROVED** [review]

**Comment by jturner65** [comment]
> I tested it.
> 
> Testing with C++ and python viewer works perfectly. Testing with ReplicaCAD_quickstart.py results in an all-black screen recording. Log attached. [log.txt](https://github.com/facebookresearch/habitat-sim/files/8173627/log.txt)

The issue is that the scene is specified as the NONE scene.  This seems to be due to the fact that the ReplicaCAD_quickstart is built such that it is more colab-friendly than python friendly - it relies on the user to select a scene from the available scene dropdown cell, before the cell that launches sim and displays the scene is launched.

**Comment by aclegg3** [comment]
> Pulled. Re-tested. Does this video look sensible? I can't imagine where the agent has been spawned.

With the new NavMeshes, the closet behind the closed door is cutoff from the rest of the scene by default for the fully dynamic spaces (apt_#). With the default seed, the agent spawns inside the closet for apt_0. 😆

**Comment by dhruvbatra** [comment]
Thanks. 

> we could choose apt_1 for the default, change the seed, or modify the scenes to include the closet in the primary navmesh component (ignoring the door). 

Modifying scenes sounds like an overkill. Either apt_1 or changing seed will work, whichever is easier.

**Comment by aclegg3** [comment]
Update 03/07: added missing sofa receptacle annotations.

**Pull request merged**
