### PR TITLE
--[BE Week] Remove ptex support

### PR DESCRIPTION
**Pull request by jturner65**
## Motivation and Context
PTEX Support is no longer desired in habitat-sim, so this support is being removed. This consists of removing cmake-driven flags intended to drive PTEX mesh handling, and PTEX-oriented classes and shaders from within the Simulator resource loading and rendering paths.

## How Has This Been Tested
Current c++ and python tests pass

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jturner65** [comment]
TODO: I still need to create an appropriate BE ticket on the tracker.

**Comment by 0mdc** [comment]
We'll want to either remove those PTEX enum entries, or treat/annotate them as errors:

- `SupportedMeshType::PTEX_MESH` (`src/esp/assets/BaseMesh.h`)
- `DrawableType::PTexMesh` (`src/esp/gfx/Drawable.h`)

**Comment by 0mdc** [comment]
Nit: `PTexMeshDrawable` is still being referred to in some comments:

- `src/esp/gfx/Drawable.h`
- `src/esp/scene/SceneGraph.h`

**Review by 0mdc — APPROVED** [review]
LGTM!

**Pull request merged**
