### PR TITLE
Add HM3DSem category mappings file

### PR DESCRIPTION
**Pull request by srama2512**
## Motivation and Context

This PR adds a file to map raw HM3DSem category names to 40 standard MP3D categories. The first column contains the raw name from HM3DSem annotations, the second column contains the typo fix to the raw name (if any), and the third column contains one of 40 standard MP3D categories. This is particularly useful in generating HM3DSem ObjectNav episodes, where we used the following code snippet to map raw names to an HM3D ObjectNav category.

```
# Create mapping from raw names to categories
HM3D_RAW_TO_CAT_MAPPING = {}
with open("<PATH_TO_HABITAT_SIM>/data/hm3d_semantics/hm3dsem_category_mappings.tsv", "r") as tsv_file:
    tsv_reader = csv.reader(tsv_file, delimiter="\t")
    is_first_row = True
    for row in tsv_reader:
        if is_first_row:
            is_first_row = False
            continue
        orig_raw_name = row[0].strip().lower()
        fixed_raw_name = row[1].strip().lower()
        cat_name = row[2]
        # Override the category name for plant
        if "plant" in fixed_raw_name or "flower" in fixed_raw_name:
            cat_name = "plant"
        HM3D_RAW_TO_CAT_MAPPING[orig_raw_name] = cat_name
        HM3D_RAW_TO_CAT_MAPPING[fixed_raw_name] = cat_name

# For a given raw name, decide whether the object is an ObjectNav goal
GOAL_CATEGORIES = ["chair", "bed", "plant", "toilet", "tv_monitor", "sofa"]
is_goal_object = HM3D_RAW_TO_CAT_MAPPING[given_raw_name.strip().lower()] in GOAL_CATEGORIES
```

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
You'll need to run pre-commit on this.

**Comment by srama2512** [comment]
> You'll need to run pre-commit on this.

I ran pre-commit. But it removed tabs and replaced them with spaces, which goes against the definition of the tsv file. How do I prevent this from happening?

**Comment by Skylion007** [comment]
Oh, you probably need to add an exclude to the replace tabs pre-commit hook in the pre-commit config.

**Comment by Skylion007** [comment]
@srama2512 Just add it to this regex: https://github.com/facebookresearch/habitat-sim/blob/dd1b1ff7aedfe6a109da61f654f0979389b465c2/.pre-commit-config.yaml#L35

**Review by aclegg3 — APPROVED** [review]

**Pull request merged**
