### PR TITLE
Rename the cameraNode_ to visualSensorNode_ in Viewer

### PR DESCRIPTION
**Pull request by bigbike**
## Motivation and Context
This is to improve the readability of the code.
**Before**: There were two "cameras" in the viewer. One is the RenderCamera, which, by the name, is used to render the scene. And the other camera is conceptual, which actually is the "visual sensor" on the agent. 

**After**: Renamed the 2nd camera mentioned above to "visual sensor", which conforms to our logic everywhere in the simulator. This makes the code a bit easier to understand, and maintain.

## How Has This Been Tested
Local run with test model files.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bigbike** [comment]
This PR is ready to be reviewed. Thanks.

**Comment by dhruvbatra** [comment]
"Visual Sensor" is ambiguous (does it provide RGB or RGB-D). Could we use a more descriptive name?

**Comment by bigbike** [comment]
> "Visual Sensor" is ambiguous (does it provide RGB or RGB-D). Could we use a more descriptive name?

Makes sense.
It is just RGB sensor. I can call it "rgbSensor"

**Comment by bigbike** [comment]
I also noticed that in the Sensor.h we defined a sensor type as COLOR. 
So maybe I can call it colorSensor.

**Comment by bigbike** [comment]
Updated the name to "colorSensor". 

@dhruvbatra : does it address your concerns?

**Comment by dhruvbatra** [comment]
I like colorSensor much better. There's still the ambiguity of whether color is RGB or HSV or some other space, but I can live with that.

**Comment by bigbike** [comment]
> I like colorSensor much better. There's still the ambiguity of whether color is RGB or HSV or some other space, but I can live with that.

Then how about the other choice "rgbSensor"?

**Comment by dhruvbatra** [comment]
Sounds good to me.

**Comment by bigbike** [comment]
Cool. Updated it to rgbSensor.
Once the Ci tests are finished, I will merge it in.

Thanks!

**Pull request merged**
