### PR TITLE
Fix bindings cyclic type references and type annotations

### PR DESCRIPTION
**Pull request by mosra**
## Motivation and Context

- The binding code was referencing types that weren't known yet to pybind (either described later or not at all), causing the exported functions to have C++ names in their signatures, making them unusable from Python.
- Various Python APIs had wrong type annotations. In particular, the `np.array()` is a function, the correct type is `np.ndarray`. Unfortunately that's all we can annotate for now; type, dimensionality and size needs to wait until https://github.com/numpy/numpy/issues/7370.

Discovered while running [m.css](https://mcss.mosra.cz) on the project to generate docs for the Python side.

## How Has This Been Tested

It builds? :sunglasses: 

This brings no functional change, so should be easy to review and merge.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by erikwijmans** [comment]
If it build, it ships! Thank you for fixing these.  I will attempt to remember that `np.array` is not a type (I always forget that....)

**Comment by mosra** [comment]
I really hope proper type annotations for numpy types are going to land sometime soon so we can use `np.ndarray[float, [3]]` and such. The current way doesn't really tell much about the expected type, being only slightly better than doing `def foo() -> object` :sweat_smile:

**Comment by mosra** [comment]
Ready to merge? Or should I wait for one review? :)

**Comment by erikwijmans** [comment]
Should be good to land!

**Pull request merged**
